language: node_js
node_js:
  - "13"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - npm ci
  - npm run build

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  repo: vdadonov/vdadonov.github.io
  local-dir: public
  on:
    branch: master

